name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag python-app:$(date +%s)

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Tag Docker image
      run: docker tag python-app:$(date +%s) ${{ secrets.DOCKER_USERNAME }}/python-app:latest

    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/python-app:latest


  deploy:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy the Docker container
      run: |
  
       docker pull ${{ secrets.DOCKER_USERNAME }}/python-app:$(date +%s)
        
        # Run the Docker container (you can modify the ports as per your needs)
        docker run -d -p 4000:80 ${{ secrets.DOCKER_USERNAME }}/python-app:$(date +%s)
